### ISSUE TITLE
Use native driver through TCP to connect to the Event Store instead of HTTP

### ISSUE THREAD

**Issue by hecrj** [rom-rb/rom-event_store#1]
Currently there is no documentation about how to use the Event Store TCP protocol. However, I could try to understand how it works by looking at some already implemented drivers. But that will take some time...

**Comment by solnic** [comment]
Hey there :) Have you seen this: https://github.com/mathieuravaux/eventstore-ruby?

**Comment by hecrj** [comment]
Wow, that looks really nice! I'll try to wire it asap :D

**Comment by solnic** [comment]
Awesome! I'd love to try out this adapter and put together an article on rom-rb.org about this. Event sourcing is something that should play really nice with ROM.

**Comment by hecrj** [comment]
That would be great!

It seems that the gem `eventstore` at RubyGems is a different one though: https://rubygems.org/gems/eventstore

I'm thinking of forking it and pushing it myself.
